//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: imageprocess.proto

package io.grpc.examples.imageprocess;

@kotlin.jvm.JvmSynthetic
public inline fun imageProcessResquest(block: io.grpc.examples.imageprocess.ImageProcessResquestKt.Dsl.() -> kotlin.Unit): io.grpc.examples.imageprocess.ImageProcessResquest =
  io.grpc.examples.imageprocess.ImageProcessResquestKt.Dsl._create(io.grpc.examples.imageprocess.ImageProcessResquest.newBuilder()).apply { block() }._build()
public object ImageProcessResquestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.grpc.examples.imageprocess.ImageProcessResquest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.grpc.examples.imageprocess.ImageProcessResquest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.grpc.examples.imageprocess.ImageProcessResquest = _builder.build()

    /**
     * <code>string timestamp = 1;</code>
     */
    public var timestamp: kotlin.String
      @JvmName("getTimestamp")
      get() = _builder.getTimestamp()
      @JvmName("setTimestamp")
      set(value) {
        _builder.setTimestamp(value)
      }
    /**
     * <code>string timestamp = 1;</code>
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }

    /**
     * <code>bytes image = 2;</code>
     */
    public var image: com.google.protobuf.ByteString
      @JvmName("getImage")
      get() = _builder.getImage()
      @JvmName("setImage")
      set(value) {
        _builder.setImage(value)
      }
    /**
     * <code>bytes image = 2;</code>
     */
    public fun clearImage() {
      _builder.clearImage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.grpc.examples.imageprocess.ImageProcessResquest.copy(block: io.grpc.examples.imageprocess.ImageProcessResquestKt.Dsl.() -> kotlin.Unit): io.grpc.examples.imageprocess.ImageProcessResquest =
  io.grpc.examples.imageprocess.ImageProcessResquestKt.Dsl._create(this.toBuilder()).apply { block() }._build()
