//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: imageprocess.proto

package io.grpc.examples.imageprocess;

@kotlin.jvm.JvmSynthetic
public inline fun imageProcessResponse(block: io.grpc.examples.imageprocess.ImageProcessResponseKt.Dsl.() -> kotlin.Unit): io.grpc.examples.imageprocess.ImageProcessResponse =
  io.grpc.examples.imageprocess.ImageProcessResponseKt.Dsl._create(io.grpc.examples.imageprocess.ImageProcessResponse.newBuilder()).apply { block() }._build()
public object ImageProcessResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.grpc.examples.imageprocess.ImageProcessResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.grpc.examples.imageprocess.ImageProcessResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.grpc.examples.imageprocess.ImageProcessResponse = _builder.build()

    /**
     * <code>string message = 1;</code>
     */
    public var message: kotlin.String
      @JvmName("getMessage")
      get() = _builder.getMessage()
      @JvmName("setMessage")
      set(value) {
        _builder.setMessage(value)
      }
    /**
     * <code>string message = 1;</code>
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.grpc.examples.imageprocess.ImageProcessResponse.copy(block: io.grpc.examples.imageprocess.ImageProcessResponseKt.Dsl.() -> kotlin.Unit): io.grpc.examples.imageprocess.ImageProcessResponse =
  io.grpc.examples.imageprocess.ImageProcessResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()
